notifications:
  email: false
language: python
dist: xenial
sudo: required
python:
  - '3.7'
  - '3.6'
  - '3.5'
install:
  - pip install .
  - pip install -r test-requirements.txt
script:
  - py.test --pep8